### ISSUE TITLE
Device Scanner Service

### ISSUE THREAD

**Issue by KarloX2** [industrial-edge/inventory-scan-and-analyze-your-network#2]
Hi!

On the Industrial Edge Hub > Library page, there's a "Device Scanner Service V1.0.2" listed. Is this one of the things that the Inventory App uses?
There seems to be no documentation for it. The according link on the Hub's lib entry is broken. Is there some doc for it somewhere?

Thanks

**Comment by Patrick-Warlamow** [comment]
Hi,

There is currently no documentation. You don't need documentation for the Device Scanner. This app has no web interface and no settings. It is only an app with an interface to Inventory.

The Device Scanner V1.0.2 which is currently available in the Industrial Hub is compatible with Inventory V1.0.5. There is a known issue with a popup window that can be dismissed by the user.
The V1.1.0 Device Scanner will be available on the Industrial Hub at the end of this month.

best regards

**Comment by KarloX2** [comment]
Thanks, @Patrick-Warlamow , for explaining this.

One more question: Is it possible to make either the Device Scanner or the Inventory App publish the found devices on the Edge Data Bus (or similar software interface)?

**Comment by Patrick-Warlamow** [comment]
Hi, 
Yes it is possible, there is a section on this in the Inventory documentation:

https://cache.industry.siemens.com/dl/dl-media/908/109781908/att_1032030/v2/Inventory_application_en-US/en-US/index.html#treeId=17f5d2c064ef21f0431a5c42c81dd4cb

**Comment by KarloX2** [comment]
@Patrick-Warlamow , thanks. But your link ends up in a "not found" message. Can you please check?

**Comment by Patrick-Warlamow** [comment]
for me it works fine.

do you have access to the Siemens Product support:

https://support.industry.siemens.com/cs/document/109781908/inventory-application?dti=0&lc=en-DE

**Comment by KarloX2** [comment]
@Patrick-Warlamow , one more question please: Is is possible to have the Inventory app perform scans periodically in the background and have the results published to the data bus? Or do I need to initiate every scan manually on the Web UI?

**Comment by Patrick-Warlamow** [comment]
@KarloX2 With the version released today, the inventory app cannot perform regular scans and publish the data on the data bus. This is intentionally not done because scanning is a very costly operation for the factory network.

**Comment by KarloX2** [comment]
@Patrick-Warlamow , thanks! Is there a new-features list for the latest release of Inventory available somewhere or could you post it here?

**Comment by Patrick-Warlamow** [comment]
@KarloX2 unfortunately there is no current list at the moment, it will be ready next week. i can share it with you next week.
